version: '2'
services:
    hymaya-app:
        image: hymaya
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hymaya-mysql:3306/hymaya?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hymaya-mysql:
        extends:
            file: mysql.yml
            service: hymaya-mysql
